version: '3'
volumes:
  node_modules:
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app:delegated
      - node_modules:/usr/src/app/node_modules
    tty: true
    command: swagger-editor-live swagger.yml
